# CMake generated Testfile for 
# Source directory: /home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/src/lorawan/examples
# Build directory: /home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/cmake-cache/src/lorawan/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-simple-network-example "ns3.42-simple-network-example-default")
set_tests_properties(ctest-simple-network-example PROPERTIES  WORKING_DIRECTORY "/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/src/lorawan/examples/CMakeLists.txt;16;build_lib_example;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/src/lorawan/examples/CMakeLists.txt;0;")
add_test(ctest-network-server-example "ns3.42-network-server-example-default")
set_tests_properties(ctest-network-server-example PROPERTIES  WORKING_DIRECTORY "/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/src/lorawan/examples/CMakeLists.txt;16;build_lib_example;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/src/lorawan/examples/CMakeLists.txt;0;")
add_test(ctest-complete-network-example "ns3.42-complete-network-example-default")
set_tests_properties(ctest-complete-network-example PROPERTIES  WORKING_DIRECTORY "/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/src/lorawan/examples/CMakeLists.txt;16;build_lib_example;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/src/lorawan/examples/CMakeLists.txt;0;")
add_test(ctest-adr-example "ns3.42-adr-example-default")
set_tests_properties(ctest-adr-example PROPERTIES  WORKING_DIRECTORY "/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/src/lorawan/examples/CMakeLists.txt;16;build_lib_example;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/src/lorawan/examples/CMakeLists.txt;0;")
add_test(ctest-lorawan-energy-model-example "ns3.42-lorawan-energy-model-example-default")
set_tests_properties(ctest-lorawan-energy-model-example PROPERTIES  WORKING_DIRECTORY "/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/src/lorawan/examples/CMakeLists.txt;16;build_lib_example;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/src/lorawan/examples/CMakeLists.txt;0;")
add_test(ctest-aloha-throughput "ns3.42-aloha-throughput-default")
set_tests_properties(ctest-aloha-throughput PROPERTIES  WORKING_DIRECTORY "/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/src/lorawan/examples/CMakeLists.txt;16;build_lib_example;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/src/lorawan/examples/CMakeLists.txt;0;")
add_test(ctest-parallel-reception-example "ns3.42-parallel-reception-example-default")
set_tests_properties(ctest-parallel-reception-example PROPERTIES  WORKING_DIRECTORY "/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/src/lorawan/examples/CMakeLists.txt;16;build_lib_example;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/src/lorawan/examples/CMakeLists.txt;0;")
add_test(ctest-frame-counter-update "ns3.42-frame-counter-update-default")
set_tests_properties(ctest-frame-counter-update PROPERTIES  WORKING_DIRECTORY "/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/src/lorawan/examples/CMakeLists.txt;16;build_lib_example;/home/bonice/Bureau/knowledge/ns-allinone-3.42/ns-3.42/src/lorawan/examples/CMakeLists.txt;0;")
